---
title: Miami College of Design
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
  faculty:
    title: Faculty
    output: true
  header:
    title: Header
    output: true
  home-page:
    title: Home Page
    output: true
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    post_date: ''
    post_image: ''
    post_url: ''
- scope:
    path: ''
    type: header
  values:
    navbar_logo: ''
    responsive_logo: ''
- scope:
    path: ''
    type: home_page
  values:
    intro_button_text: We
    intro_button_url: ''
    intro_title: We support future leaders in design and innovation.
    intro_bg_image: ''
    one_image: ''
    one_image_title: ''
    one_image_description: ''
    two_image: ''
    two_image_title: ''
    two_image_description: ''
    four_image: ''
    four_image_title: ''
    four_image_description: ''
    video_bg_image: ''
    video_url: https://www.youtube.com/embed/lwheP-Ggca8?rel=0
    our_mission_text: ''
    mission_button_text: ''
    mission_button_url: ''
    bottomfold_two_image: ''
- scope:
    path: ''
    type: pages
  values:
    sidemenu:
      sidemenu_link_ID: Title for sidemenu
    one_image: "/uploads/eye.png"
    two_image: "/uploads/blueprint.jpg"
    header_image: "/uploads/about_featured.png"
    header_title: ''
    header_subtitle: ''
- scope:
    path: ''
    type: events
  values:
    layout: single_event
    event_venue: ''
    event_date: ''
    event_image: ''
    one_image: "/uploads/eye.png"
    two_image: "/uploads/blueprint.jpg"
    header_image: "/uploads/about_featured.png"
- scope:
    path: ''
    type: news
  values:
    layout: single_news
    news_location: ''
    news_date: ''
    news_image: ''
    one_image: "/uploads/eye.png"
    two_image: "/uploads/blueprint.jpg"
    header_image: "/uploads/about_featured.png"
repository: git@github.com:oxmint/miami.git
email: hello@miamicollegeofdesign.com
description: The super wonderful cool homepage for the Miami College of Design in
  Wynwood
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
navbar_logo: "/uploads/logo-0-410d08.png"
facebook: http://facebook.com/miamicollegeofdesign
twitter: http://twitter.com/iam_mcod
instagram: http://instagram.com/miamicollegeofdesign
google_plus: https://plus.google.com/b/101318520222028561228/101318520222028561228
snapchat: https://www.snapchat.com/add/iam_mcod
github: https://github.com/MiamiCollegeDesign
footer_menu:
  Academic Policies: 
  Standards of Conduct: 
  Blog: 
