---
title: Miami College of Design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
  values:
    connect_with_us_background_image: ''
    image_1_by_1: ''
    title_1_by_1: ''
    description_1_by_1: ''
    image_2_by_2: ''
    title_2_by_2: ''
    description_2_by_2: ''
    image_4_by_4: ''
    title_4_by_4: ''
    description_4_by_4: ''
    intro_video_link: ''
email: your-email@domain.com
description: ''
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
