---
title: Miami College of Design
timezone: UTC
collections:
  events:
    title: Events
    output: true
  home-page:
    title: Home Page
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: home_page
  values:
    intro_title: We support future leaders in design and innovation.
    intro_bg_image: ''
    one_image: ''
    one_image_title: ''
    one_image_description: ''
    two_image: ''
    two_image_title: ''
    two_image_description: ''
    four_image: ''
    four_image_title: ''
    four_image_description: ''
    video_bg_image: ''
    video_url: https://www.youtube.com/embed/lwheP-Ggca8?rel=0
    our_mission_text: ''
    bottomfold_two_image: ''
- scope:
    path: ''
    type: pages
  values:
    navbar_logo: "/uploads/logo.png"
    coloured_logo: '/uploads/iam-blue.png'
    one_image: '/uploads/eye.png'
    two_image: '/uploads/blueprint.jpg'
    header_image: '/uploads/about_featured.png'
    header_title: ''
    header_subtitle: ''
    sidemenu:
        : ''
- scope:
    path: ''
    type: events
  values:
    event_venue: ''
    event_date: ''
    event_image: ''
email: your-email@domain.com
description: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
